global:
  resolve_timeout: 5m
  smtp_smarthost: '10.0.1.160:25' # 郵箱smtp伺服器代理
  smtp_from: 'cli-prometheus@104.com.tw' # 傳送郵箱名稱
route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m
  receiver: 'email'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
- name: 'email' # 警報
  email_configs: # 郵箱配置
  - to: 'kevin.wang@104.com.tw'  # 接收警報的email配置
    html: '{{ template "test.html" . }}' # 設定郵箱的內容模板
    headers: { Subject: "[WARN] 報警郵件"} # 接收郵件的標題
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
templates:
          - 'template/*.tmpl'
